// <auto-generated />
namespace FIT.Diploma.Server.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddBookmakerOddsStats : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBookmakerOddsStats));
        
        string IMigrationMetadata.Id
        {
            get { return "201712231810236_Add BookmakerOddsStats"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
